outputs:
  - device: KATANA 1
    max_patches: 5
    map:
      0: 4
      1: 2
      2: 0
      3: 1
      4: 3

inputs:
  - device: ZOOM G Series
    type: zoomg3
    output_device: ZOOM G Series

callbacks: true
